local settings = {
    -- every line should be same width without escaped \
    header = {
        type = "text",
        oldfiles_directory = false,
        align = "center",
        fold_section = false,
        title = "Header",
        margin = 0,
        content = {
  	    "  /$$$$$$   /$$$$$$   /$$$$$$   /$$$$$$   /$$$$$$   /$$$$$$  /$$    /$$ /$$ /$$$$$$/$$$$  ",
 	    " / $$__ $$ /$$__  $$ /$$__  $$ /$$__  $$ /$$__  $$ /$$__  $$|  $$  /$$/| $$| $$_  $$_  $$ ",
	    "| $$  | $$| $$$$$$$$| $$$$$$$$| $$  | $$| $$$$$$$$| $$  |___/ | $$/$$/ | $$| $$ | $$ | $$ ",
	    "| $$  | $$| $$_____/| $$_____/| $$  | $$| $$_____/| $$        |  $$$/  | $$| $$ | $$ | $$ ",
	    "| $$$$$$$/|  $$$$$$$|  $$$$$$$| $$$$$$$/|  $$$$$$$| $$         |  $/   | $$| $$ | $$ | $$ ",
	    "| $$____/  |_______/ |_______/| $$____/  |_______/|__/          |_/    |__/|__/ |__/ |__/ ",
	    "| $$                          | $$                                                        ",
            "|__/                          |__/                                                        ",
            "                         $     f.  .;@y               ",
            "                         1 [  //   ~g@$               ",
            " .`^-_                      ,i v<    ~@@~             ",
            "   -. ~o.                   '' `      ~``             ",
            "     ' . }L .          .                              ",
            "        `  ^`     .:g@@@@@@y      .''''Rg             ",
            "                  4@@@@@@@@@yy_ ::?:`'4P              ",
            "                  g@@@@@@@@@@@@gy~'''``               ",
            "                  $@@@@@@@@@@@@@@@gyyyy__   .         ",
            "          ,':.  y@@@@@@@@@@@@@@@@@@@@@@@@ggy_         ",
            "         :   `' _@@@@@@@@@@@@@@@@@@@@@@@@@@@@$wy      ",
            "         `'.`    g@@@@@@@@@@@@@@PMR@@@@@@@@@@@@@@ggW*=",
            "           . y@@@@@@~~TTTFFR@@ yg@@@@@@@@@@@@@@@@@@DZZ",
            "         . j@@@@@@@_``   ``:4@$@@@@@@@@@@@@@@@@@@@@@gy",
            "          =@@@@@@@@@@gyy_.```~T@@@@@@@@@@@@@@@@@@@@@@w",
            "          `~@@@@@@@@@@@@@@$y. :@@@@@@@@@@@@@@@@@@@@@@@",
            "           g@@@@@@@@@@@@@@@@s_`ME@@@@@@@@@@@@@@@@@@@$w",
            "          `g@@@@@@@@@@@@M@@@@y'``F9@@@@@@@@@@@@@@@@@@L",
            "           @@@@@@@RAMTjg@@g@R   :````$@@@@@@@@@@@@@@@g",
            "           4@@MT@@_yy:rTEa@M~`  ::gg@@@@@@@@@@@@@@@@@@",
            "        . ` `;a@@AF~y::```   .::wg@@@@@@@@@@@@@@@@@@@@",
            "           zF``@@`@m`F``   : :::@@@@@@@@@@@@@@@@@@@@@@",
            "      `  _F    y`__::`. ..:::`:a@@@@@@@@@@@@@@@@@@@@@@",
            "       .+~    gK0@@@@gay__jyy:4@@@@@@@@@@@@@@@@@@@@@@@",},
        highlight = "Statement",
        default_color = "",
        oldfiles_amount = 0,
    },
    -- name which will be displayed and command
    body = {
        type = "mapping",
        oldfiles_directory = false,
        align = "center",
        fold_section = false,
        title = "Basic Commands",
        margin = 0,
        content = {
	    { " New File", "lua require'startup'.new_file()", "<leader>nf" },
            { " Find File", "Telescope find_files", "<leader>ff" },
            { " Recent Files", "Telescope oldfiles", "<leader>of" },
            { " File Browser", "Telescope file_browser", "<leader>fb" },
	    { "󰏫 Edit Config", "e /home/ianrb/.config/nvim/init.lua", "<leader>ec" },
        },
        highlight = "String",
        default_color = "",
        oldfiles_amount = 0,
    },
    footer = {
        type = "text",
        oldfiles_directory = false,
        align = "center",
        fold_section = false,
        title = "Footer",
        margin = 0,
        content = { "" },
        highlight = "Number",
        default_color = "",
        oldfiles_amount = 0,
    },

    options = {
        mapping_keys = true,
        cursor_column = 0.5,
        empty_lines_between_mappings = true,
        disable_statuslines = true,
        paddings = { 1, 3, 3, 0 },
    },
    mappings = {
        execute_command = "<CR>",
        open_file = "o",
        open_file_split = "<c-o>",
        open_section = "<TAB>",
        open_help = "?",
    },
    colors = {
        background = "#1f2227",
        folded_section = "#56b6c2",
    },
    parts = { "header", "body", "footer" },
}
return settings
